prompt --application/deployment/install/install_create_status_code_tables
begin
--   Manifest
--     INSTALL: INSTALL-create status code tables
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>114
,p_default_id_offset=>25570339520000058
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(6060579183695740303)
,p_install_id=>wwv_flow_imp.id(8903256921486151716)
,p_name=>'create status code tables'
,p_sequence=>140
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create table eba_proj_status_cats (',
'    id                     number primary key,',
'    row_version_number      number,',
'    category               varchar2(100),',
'    display_sequence       number,',
'    is_active_yn           varchar2(1) default ''Y'' not null,',
'    --',
'    created                timestamp(6) with local time zone,',
'    created_by             varchar2(255),',
'    updated                timestamp(6) with local time zone,',
'    updated_by             varchar2(255)',
'    )',
'/',
'',
'create table eba_proj_color_codes (',
'    id                     number primary key,',
'    row_version_number     number,',
'    color_name             varchar2(255) not null,',
'    color_code             varchar2(10) default ''#F2F2F2'' not null,',
'    sprite_url             varchar2(255),',
'    sprite_position_x      number default 0,',
'    sprite_position_y      number default 0,',
'    display_sequence       number,',
'    is_active_yn           varchar2(1),',
'    --',
'    created                timestamp(6) with local time zone,',
'    created_by             varchar2(255),',
'    updated                timestamp(6) with local time zone,',
'    updated_by             varchar2(255)',
'    )',
'/',
'',
'create table eba_proj_status_codes (',
'    id                     number primary key,',
'    row_version_number     number,',
'    status_short_desc      varchar2(255) not null,',
'    is_closed_status       varchar2(1) default ''N'' not null,',
'    color_code_id          number references eba_proj_color_codes(id),',
'    is_active_yn           varchar2(1) default ''Y'' not null,',
'    IS_DESIRABLE_YN        varchar2(1),',
'    display_sequence       number,',
'    --',
'    created                timestamp(6) with local time zone,',
'    created_by             varchar2(255),',
'    updated                timestamp(6) with local time zone,',
'    updated_by             varchar2(255)',
'    )',
'/',
'',
'create index eba_proj_status_code_color_idx on eba_proj_status_codes(color_code_id);',
'',
'create table eba_proj_status_sizes (',
'    id                     number primary key,',
'    project_size           varchar2(50),',
'    size_description       varchar2(4000),',
'    display_sequence       number,',
'    --',
'    created                timestamp(6) with local time zone,',
'    created_by             varchar2(255),',
'    updated                timestamp(6) with local time zone,',
'    updated_by             varchar2(255)',
'    )',
'/',
'',
'CREATE OR REPLACE TRIGGER eba_proj_status_sizes_BIU',
'   before insert or update on eba_proj_status_sizes',
'   for each row',
'begin',
'',
'   if :new.ID is null then',
'     :new.id := to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'');',
'   end if;',
'   ',
'   if inserting then',
'       :new.created := localtimestamp;',
'       :new.created_by := nvl(apex_application.g_user,user);',
'   end if;',
'   if inserting or updating then',
'       :new.updated := localtimestamp;',
'       :new.updated_by := nvl(apex_application.g_user,user);',
'   end if;',
'end;',
'/',
'',
'ALTER TRIGGER eba_proj_status_sizes_BIU ENABLE',
'/',
'',
'insert into eba_proj_status_sizes (id, project_size, size_description, display_sequence) values (1, ''Small'', '''', 1);',
'insert into eba_proj_status_sizes (id, project_size, size_description, display_sequence) values (2, ''Medium'', '''', 2);',
'insert into eba_proj_status_sizes (id, project_size, size_description, display_sequence) values (3, ''Large'', '''', 3);',
'insert into eba_proj_status_sizes (id, project_size, size_description, display_sequence) values (4, ''X-Large'', '''', 4);',
'',
'commit;',
'',
'create table eba_proj_involvement_levels (',
'    id                      number primary key,',
'    involvement_level       varchar2(50),',
'    involvement_description varchar2(4000),',
'    percentage              number not null,',
'    display_sequence        number,',
'    --',
'    created                timestamp(6) with local time zone,',
'    created_by             varchar2(255),',
'    updated                timestamp(6) with local time zone,',
'    updated_by             varchar2(255)',
'    )',
'/',
'',
'create or replace trigger eba_proj_invlvmnt_levels_biu',
'    before insert or update on eba_proj_involvement_levels',
'    for each row',
'begin',
'    if :new.id is null then',
'        :new.id := to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'');',
'    end if;',
'    if inserting then',
'        :new.created := localtimestamp;',
'        :new.created_by := nvl(wwv_flow.g_user,user);',
'    end if;',
'    :new.updated := localtimestamp;',
'    :new.updated_by := nvl(wwv_flow.g_user,user);    ',
'end;',
'/',
'',
'alter trigger eba_proj_invlvmnt_levels_biu enable',
'/',
'',
'insert into eba_proj_involvement_levels (involvement_level, involvement_description, percentage, display_sequence)',
'values (''Full'', '''', 100, 10);',
'insert into eba_proj_involvement_levels (involvement_level, involvement_description, percentage, display_sequence)',
'values (''Half'', '''', 50, 20);',
'insert into eba_proj_involvement_levels (involvement_level, involvement_description, percentage, display_sequence)',
'values (''Quarter'', '''', 25, 30);',
'insert into eba_proj_involvement_levels (involvement_level, involvement_description, percentage, display_sequence)',
'values (''Partial'', '''', 10, 40);',
'',
'commit;',
'',
''))
);
wwv_flow_imp.component_end;
end;
/
