prompt --application/deployment/install/install_access_control_tables
begin
--   Manifest
--     INSTALL: INSTALL-Access Control Tables
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(2739992647389364866)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'Access Control Tables'
,p_sequence=>30
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create table eba_intrack_access_levels (',
'    id                      number              not null',
'                                                constraint eba_intrack_acc_lev_pk',
'                                                primary key,',
'    access_level            varchar2(30)        not null',
'                                                constraint eba_intrack_ac_lv_ac_lv_ck',
'                                                check (access_level in (',
'                                                    ''Administrator'',',
'                                                    ''Contributor'',',
'                                                    ''Reader'' )),',
'    row_version             number )',
'/',
'create unique index eba_intrack_accs_lvls_uk on eba_intrack_access_levels(access_level);',
'',
'create table eba_intrack_users (',
'    id                      number              not null',
'                                                constraint eba_intrack_users_pk',
'                                                primary key,',
'    username                varchar2(255)       not null',
'                                                constraint eba_intrack_usrs_un_ck',
'                                                check (upper(username)=username),',
'    access_level_id         number              not null',
'                                                constraint eba_intrack_us_ac_lv_fk',
'                                                references eba_intrack_access_levels,',
'    account_locked          varchar2(1)         not null',
'                                                constraint eba_intrack_us_ac_lckd_ck',
'                                                check (account_locked in (''Y'',''N'')),',
'    first_name              varchar2(255),',
'    last_name               varchar2(255),',
'    country_id              varchar2(255),',
'    email                   varchar2(255),',
'    additional_info         varchar2(4000),',
'    flex_01                 varchar2(4000),',
'    flex_02                 varchar2(4000),',
'    flex_03                 varchar2(4000),',
'    flex_04                 varchar2(4000),',
'    --',
'    row_version             number,',
'    created_by              varchar2(255)       not null,',
'    created                 timestamp with time zone,',
'    updated_by              varchar2(255),',
'    updated                 timestamp with time zone )',
'/',
'',
'create unique index eba_intrack_users_uk on eba_intrack_users (username);',
'',
'create index eba_intrack_us_acc_lv_i on eba_intrack_users (access_level_id);',
'',
'create or replace trigger eba_intrack_users_biu',
'    before insert or update on eba_intrack_users',
'    for each row',
'begin',
'    if inserting then',
'        if :new.id is null then',
'            :new.id := eba_intrack.gen_id();',
'        end if;',
'        :new.created_by         := nvl(v(''APP_USER''), USER);',
'        :new.created            := current_timestamp;',
'        :new.row_version        := 1;',
'        if :new.account_locked is null then',
'            :new.account_locked := ''N'';    ',
'        end if;',
'    end if;',
'    if updating then',
'            :new.updated_by         := nvl(v(''APP_USER''), USER);',
'            :new.updated            := current_timestamp;',
'            :new.row_version        := nvl(:old.row_version,1) + 1;                                   ',
'    end if;',
'    -- Always store username as upper case',
'    :new.username := upper(:new.username);',
'end;',
'/',
'',
'alter trigger eba_intrack_users_biu enable;',
'',
'create or replace trigger eba_intrack_users_bd',
'    before delete on eba_intrack_users',
'    for each row',
'declare',
'    pragma autonomous_transaction;',
'begin',
'    -- Disallow deletes to a user''s own record unless last one.',
'    if v(''APP_USER'') = upper(:old.username) then',
'       for c1 in (',
'          select count(*) cnt',
'            from eba_intrack_users',
'           where id != :old.id )',
'       loop',
'          if c1.cnt > 0 then',
'             raise_application_error(-20002, ''Delete disallowed, you cannot delete your own access control details.'');',
'          end if;',
'       end loop;',
'    end if;    ',
'end;',
'/',
'',
'alter trigger eba_intrack_users_bd enable;',
'',
'create table eba_intrack_error_lookup (',
'    constraint_name         varchar2(30)        not null',
'                                                constraint eba_intrack_error_lookup_pk',
'                                                primary key,',
'    message                 varchar2(4000)      not null,',
'    language_code           varchar2(30)        not null',
')',
'/',
'    ',
'create unique index eba_intrack_error_lookup_uk on eba_intrack_error_lookup (constraint_name,language_code);',
'/',
'',
'insert into eba_intrack_access_levels (id, access_level) values (3,''Administrator'');',
'insert into eba_intrack_access_levels (id, access_level) values (2,''Contributor'');',
'insert into eba_intrack_access_levels (id, access_level) values (1,''Reader'');',
'',
'insert into eba_intrack_error_lookup (constraint_name, message, language_code) values (''eba_intrack_USERS_UK'', ''Username must be unique.'', ''en'');',
'',
'commit;'))
);
wwv_flow_imp.component_end;
end;
/
