prompt --application/deployment/install/install_eba_intrack_body
begin
--   Manifest
--     INSTALL: INSTALL-eba_intrack body
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(3204234062250047348)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'eba_intrack body'
,p_sequence=>380
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace package body eba_intrack as',
'',
'    -------------------------------------------------------------------------',
'    -- Generates a unique Identifier',
'    -------------------------------------------------------------------------',
'    function gen_id',
'        return number',
'    is',
'        l_id  number;',
'    begin',
'        select to_number(sys_guid(), ''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'          into l_id',
'          from dual;',
'    ',
'        return l_id;',
'    end gen_id;',
'',
'    -------------------------------------------------------------------------',
'    -- Gets the current user''s authorization level. Depends on the following:',
'    --  * If access control is currently disabled, returns highest level of 3.',
'    --  * If access control is enabled, but user is not in list, returns 0',
'    --  * If access control is enabled and user is in list, returns their',
'    --    access level.',
'    -------------------------------------------------------------------------',
'    function get_authorization_level (',
'        p_username             varchar2)',
'        return number',
'    is',
'        l_access_level_id       eba_intrack_users.access_level_id%type := 0;  -- default to lowest privilege.',
'        l_account_locked        eba_intrack_users.account_locked%type;',
'    begin',
'        -- If access control is disabled, default to highest privilege',
'        if eba_intrack_fw.get_preference_value(''ACCESS_CONTROL_ENABLED'') = ''N'' then',
'            return 3;',
'        else',
'            -- Query for user''s access level, throws no_data_found if no user',
'            select access_level_id,',
'                   account_locked',
'              into l_access_level_id,',
'                   l_account_locked',
'              from eba_intrack_users',
'             where username = p_username;',
'            -- Check if user''s account is locked, return 0 (no privilege), otherwise stick',
'            -- with their level.',
'            if l_account_locked = ''Y'' then',
'                return 0;',
'            end if;',
'            -- Overwrite user access level 1 with access level 2 if access control scope is PUBLIC_CONTRIBUTE',
'            if l_access_level_id = 1 and eba_intrack_fw.get_preference_value(''ACCESS_CONTROL_SCOPE'') = ''PUBLIC_CONTRIBUTE'' then',
'                return 2;',
'            end if;            ',
'        end if;',
'        return l_access_level_id;',
'    exception',
'        when no_data_found then',
'            -- If no user exists with passed username, do a final check if reader access is set to any authenticated user',
'            if eba_intrack_fw.get_preference_value(''ACCESS_CONTROL_SCOPE'') = ''PUBLIC_CONTRIBUTE'' then',
'                return 2;',
'            elsif eba_intrack_fw.get_preference_value(''ACCESS_CONTROL_SCOPE'') = ''PUBLIC_READONLY'' then',
'                return 1;',
'            else',
'                return 0;',
'            end if;           ',
'    end get_authorization_level;',
'',
'    -------------------------------------------------------------------------',
'    -- Gets the set of links displayed on the mobile details summary page (301)',
'    -- for the passed-in type',
'    -------------------------------------------------------------------------',
'    function get_mobile_incident_details',
'    (',
'      p_type    in     varchar2,',
'      p_session in     number,',
'      p_app_id  in     varchar2  default ''7140'',',
'      p_page_id in     varchar2  default ''405''',
'    ) return varchar2',
'    is',
'      l_retval varchar2(32767);',
'    begin',
'      if p_type = ''SEVERITY_ID'' then',
'        for c in',
'        (',
'          select',
'            ''<a href="''',
'                ||apex_util.prepare_url(''f?p=''||p_app_id||'':''||p_page_id||'':''||p_session||''::YES:''||p_page_id',
'                                        ||'':P''||p_page_id||''_''||p_type||'':''||apex_escape.html(v1.severity_id))',
'                ||'':">'' || v1.cnt || '' '' || apex_escape.html(v1.status) || ''</a><br />'' as severity_list_item',
'          from',
'            (',
'              select',
'                severity_name status,',
'                severity_id,',
'                count(*) cnt',
'              from',
'                eba_intrack_incidents_view',
'              where',
'                status_type = ''OPEN''',
'              group by',
'                severity_name, severity_id',
'              order by',
'                2 desc, 1',
'            ) v1',
'        )',
'        loop',
'          l_retval := l_retval || c.severity_list_item;',
'        end loop;',
'      elsif p_type = ''URGENCY_NAME'' then',
'        for c in',
'        (',
'          select',
'            ''<a href="''',
'                ||apex_util.prepare_url(''f?p=''||p_app_id||'':''||p_page_id||'':''||p_session||''::YES:''||p_page_id',
'                                        ||'':P''||p_page_id||''_''||p_type||'':''||apex_escape.html(v1.status))',
'                ||'':">'' || v1.cnt || '' '' || apex_escape.html(v1.status) || ''</a><br />'' as urgency_list_item',
'          from',
'            (',
'              select',
'                urgency_name status,',
'                count(*) cnt',
'              from',
'                eba_intrack_incidents_view',
'              where',
'                status_type = ''OPEN''',
'              group by',
'                urgency_name',
'              order by',
'                2 desc, 1',
'            ) v1',
'        )',
'        loop',
'          l_retval := l_retval || c.urgency_list_item;',
'        end loop;',
'      elsif p_type = ''STATUS_CODE'' then',
'        for c in',
'        (',
'          select',
'            ''<a href="''',
'                ||apex_util.prepare_url(''f?p=''||p_app_id||'':''||p_page_id||'':''||p_session||''::YES:''||p_page_id',
'                                        ||'':P''||p_page_id||''_''||p_type||'':''||apex_escape.html(v1.status_code))',
'                ||'':">'' || v1.cnt || '' '' || apex_escape.html(v1.status) || ''</a><br />'' as status_list_item',
'          from',
'            (',
'              select',
'                status_code,',
'                status_name status,',
'                count(*) cnt',
'              from',
'                eba_intrack_incidents_view',
'              where',
'                status_type = ''OPEN''',
'              group by',
'                status_code, status_name',
'              order by',
'                3 desc',
'            ) v1',
'        )',
'        loop',
'          l_retval := l_retval || c.status_list_item;',
'        end loop;',
'      elsif p_type = ''PRODUCT'' then',
'        for c in',
'        (',
'          select',
'            ''<a href="''',
'                ||apex_util.prepare_url(''f?p=''||p_app_id||'':''||p_page_id||'':''||p_session||''::YES:''||p_page_id',
'                                        ||'':P''||p_page_id||''_''||p_type||'':''||apex_escape.html(v1.product))',
'                ||'':">'' || v1.cnt || '' '' || apex_escape.html(v1.product) || ''</a><br />'' as product_list_item',
'          from',
'            (',
'              select',
'                PRODUCT_NAME product,',
'                count(*) cnt',
'              from',
'                eba_intrack_incidents_view',
'              where',
'                status_type = ''OPEN''',
'              group by',
'                product_name',
'              order by',
'                2 desc',
'            ) v1',
'        )',
'        loop',
'          l_retval := l_retval || c.product_list_item;',
'        end loop;',
'      elsif p_type = ''CUSTOMER_ID'' then',
'        for c in',
'        (',
'          select',
'            ''<a href="''',
'                ||apex_util.prepare_url(''f?p=''||p_app_id||'':''||p_page_id||'':''||p_session||''::YES:''||p_page_id',
'                                        ||'':P''||p_page_id||''_''||p_type||'':''||apex_escape.html(v1.id))',
'                ||'':">'' || v1.cnt || '' '' || apex_escape.html(v1.customer) || ''</a><br />'' as customer_list_item',
'          from',
'            (',
'              select',
'                customer,',
'                customer_id id,',
'                count(*) cnt',
'              from',
'                eba_intrack_incidents_view',
'              where',
'                status_type = ''OPEN''',
'              group by',
'                customer, customer_id',
'              order by',
'                2 desc',
'            ) v1',
'        )',
'        loop',
'          l_retval := l_retval || c.customer_list_item;',
'        end loop;',
'      end if;',
'      return l_retval;',
'    end get_mobile_incident_details;',
'',
'end eba_intrack;',
''))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(1688763190570115382)
,p_script_id=>wwv_flow_imp.id(3204234062250047348)
,p_object_owner=>'#OWNER#'
,p_object_type=>'PACKAGE BODY'
,p_object_name=>'EBA_INTRACK'
);
wwv_flow_imp.component_end;
end;
/
