prompt --application/deployment/install/install_incident_package_body
begin
--   Manifest
--     INSTALL: INSTALL-Incident package body
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(2814813565459769717)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'Incident package body'
,p_sequence=>280
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace package body eba_intrack_incident',
'as',
'function create_customer (',
'    p_customer_name           in varchar2 default null,',
'    p_customer_web_site       in varchar2 default null,',
'    p_customer_address        in varchar2 default null,',
'    p_customer_city           in varchar2 default null,',
'    p_customer_state          in varchar2 default null,',
'    p_customer_postal_code    in varchar2 default null,',
'    p_customer_country        in varchar2 default null',
'    ) return number',
'is',
'    l_id number;',
'    l_count integer;',
'begin',
'    select count(*) c, max(id) into l_count, l_id ',
'    from EBA_INTRACK_CUSTOMERS c',
'    where c.customer_name_upper = upper(p_customer_name);',
'    if l_count = 1 and l_id > 0 then',
'       return l_id;',
'    end if;',
'    insert into EBA_INTRACK_CUSTOMERS',
'    (',
'       customer_name,',
'       web_site,',
'       address,',
'       city,',
'       state,',
'       postal_code,',
'       COUNTRY',
'    ) values (',
'       p_customer_name,',
'       p_customer_web_site,',
'       p_customer_address,',
'       p_customer_city,',
'       p_customer_state,',
'       p_customer_postal_code,',
'       p_customer_country',
'    ) returning id into l_id;',
'    commit;',
'    return l_id;',
'end create_customer;',
'    ',
'function create_contact (',
'    p_customer_id             in number,',
'    p_new_contact_phone       in varchar2 default null,',
'    p_new_contact_email       in varchar2 default null,',
'    p_new_contact_phone_type  in varchar2 default null,',
'    p_new_contact_department  in varchar2 default null,',
'    --',
'    p_contact_first_name      in varchar2 default null,',
'    p_contact_last_name       in varchar2 default null,',
'    p_contact_email           in varchar2 default null,',
'    p_contact_department      in varchar2 default null,',
'    p_contact_phone           in varchar2 default null,',
'    p_contact_phone_type      in varchar2 default null,',
'    p_contact_country         in varchar2 default null',
'    ) return number',
'is',
'    l_id          number;',
'    l_count       integer;',
'begin',
'    select count(*) c, max(id) into l_count, l_id ',
'    from EBA_INTRACK_CUSTOMER_CONTACT c',
'    where customer_id = p_customer_id and ',
'          c.email = lower(p_contact_email);',
'    if l_count = 1 and l_id > 0 then',
'       if p_new_contact_phone is not null then',
'          update EBA_INTRACK_CUSTOMER_CONTACT',
'          set phone = p_new_contact_phone',
'          where id = l_id;',
'       end if;',
'       if p_new_contact_phone_type is not null then',
'          update EBA_INTRACK_CUSTOMER_CONTACT',
'          set phone_type = p_new_contact_phone_type',
'          where id = l_id;',
'       end if;',
'       if p_new_contact_email is not null then',
'          update EBA_INTRACK_CUSTOMER_CONTACT',
'          set email = p_new_contact_email',
'          where id = l_id;',
'       end if;',
'       if p_new_contact_department is not null then',
'          update EBA_INTRACK_CUSTOMER_CONTACT',
'          set department_name = p_new_contact_department',
'          where id = l_id;',
'       end if;',
'       return l_id;',
'    end if;',
'    insert into EBA_INTRACK_CUSTOMER_CONTACT (',
'       CUSTOMER_ID,',
'       FIRST_NAME,',
'       LAST_NAME,',
'       EMAIL,',
'       phone,',
'       phone_type,',
'       DEPARTMENT_NAME',
'       ) values (',
'       p_CUSTOMER_ID,',
'       p_contact_first_name,',
'       p_contact_last_name,',
'       p_contact_email,',
'       p_contact_phone,',
'       p_contact_phone_type,',
'       p_contact_department',
'    ) returning id into l_id;',
'    commit;',
'    return l_id;',
'end create_contact;',
'    ',
'function create_ticket (',
'    p_customer_id             in number   default null,',
'    p_customer_name           in varchar2 default null,',
'    p_customer_web_site       in varchar2 default null,',
'    p_customer_address        in varchar2 default null,',
'    p_customer_city           in varchar2 default null,',
'    p_customer_state          in varchar2 default null,',
'    p_customer_postal_code    in varchar2 default null,',
'    --                      ',
'    p_contact_id              in number   default null,',
'    p_contact_first_name      in varchar2 default null,',
'    p_contact_last_name       in varchar2 default null,',
'    p_contact_email           in varchar2 default null,',
'    p_contact_department      in varchar2 default null,',
'    p_contact_phone           in varchar2 default null,',
'    p_contact_phone_type      in varchar2 default null,',
'    p_contact_country         in varchar2 default null,',
'    --                      ',
'    p_product_id              in number   default null,',
'    p_product_version_id      in number   default null,',
'    p_product_additional_info in varchar2 default null,',
'    p_product_serial_num      in varchar2 default null,',
'    --',
'    p_urgency_id              in number   default null,',
'    p_severity_id             in number   default null,',
'    p_category_id             in number   default null,',
'    p_status_id               in number   default null,',
'    p_assignee_id             in number   default null,',
'    --',
'    p_subject                 in varchar2 default null,',
'    p_incident_description    in varchar2 default null,',
'    p_bug_number              in varchar2 default null,',
'    p_additional_info         in varchar2 default null,',
'    --',
'    p_tags                    in varchar2 default null,',
'    p_create_date_override    in timestamp with time zone default null)',
'    return varchar2',
'is',
'    l_customer_id          number := null;',
'    l_contact_id           number := null;',
'    l_id                   number := null;',
'    l_default_assignee_id  number := null;',
'    l_auto_assign          boolean := false;',
'begin',
'    --',
'    -- determine customer ID',
'    --',
'    if p_customer_id is not null then',
'       l_customer_id := p_customer_id;',
'    else',
'       l_customer_id := create_customer (',
'           p_customer_name         => p_customer_name,',
'           p_customer_web_site     => p_customer_web_site,',
'           p_customer_address      => p_customer_address,',
'           p_customer_city         => p_customer_city,',
'           p_customer_state        => p_customer_state,',
'           p_customer_postal_code  => p_customer_postal_code);',
'    end if;',
'    --',
'    -- determine contact ID',
'    --',
'    if p_contact_id is not null then',
'        l_contact_id := p_contact_id;',
'    else',
'        l_contact_id :=  create_contact (',
'            p_customer_id         => l_customer_id,',
'            p_contact_first_name  => p_contact_first_name,',
'            p_contact_last_name   => p_contact_last_name,',
'            p_contact_email       => p_contact_email,',
'            p_contact_department  => p_contact_department,',
'            p_contact_phone       => p_contact_phone,',
'            p_contact_phone_type  => p_contact_phone_type,',
'            p_contact_country     => p_contact_country);',
'    end if;',
'    ',
'    --',
'    -- determine assignee',
'    --',
'    if p_assignee_id is null and p_product_id is not null then',
'       l_auto_assign := false;',
'       for c1 in (select preference_value from eba_intrack_preferences where preference_name = ''AUTO_ASSIGN'') loop',
'          l_auto_assign := true;',
'       end loop;',
'       if l_auto_assign then',
'          for c1 in (select default_assignee_id from eba_intrack_product where id = p_product_id) loop',
'              l_default_assignee_id := c1.default_assignee_id;',
'          end loop;',
'       end if;',
'    end if;',
'    --',
'    -- create ticket',
'    --',
'    insert into EBA_INTRACK_INCIDENTS (',
'        SUBJECT,',
'        CATEGORY_ID,',
'        DESCRIPTION,',
'        PRODUCT_ID,',
'        --',
'        PRODUCT_VERSION_ID,',
'        ADDITIONAL_PRODUCT_INFO,',
'        CUSTOMER_ID,',
'        customer_contact_id,',
'        --',
'        STATUS_ID,',
'        SEVERITY_ID,',
'        URGENCY_ID,',
'        assigned_to_id,',
'        --',
'        tags, ',
'        bug_number,',
'        product_serial_num,',
'        created',
'    ) values (',
'        p_subject,',
'        p_category_id,',
'        p_incident_description,',
'        p_product_id,',
'        --',
'        p_product_version_id,',
'        p_product_additional_info,',
'        l_customer_id,',
'        l_contact_id,',
'        --',
'        p_status_id,',
'        p_severity_id,',
'        p_urgency_id,',
'        l_default_assignee_id,',
'        --',
'        p_tags,',
'        p_bug_number,',
'        p_product_serial_num,',
'        p_create_date_override',
'    ) return id into l_id;',
'    commit;',
'    return l_id;',
'',
'end create_ticket;',
'end eba_intrack_incident;',
'/',
'show errors',
'',
'',
'',
'',
'',
''))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(1688767558798115693)
,p_script_id=>wwv_flow_imp.id(2814813565459769717)
,p_object_owner=>'#OWNER#'
,p_object_type=>'PACKAGE BODY'
,p_object_name=>'EBA_INTRACK_INCIDENT'
);
wwv_flow_imp.component_end;
end;
/
