prompt --application/deployment/install/install_customers_table
begin
--   Manifest
--     INSTALL: INSTALL-customers table
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(2760226255460562117)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'customers table'
,p_sequence=>230
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create table eba_intrack_customers (',
'   id                      number         not null,',
'   row_version_number      number         not null,',
'   row_key                 varchar2(60)   not null,',
'   customer_name           varchar2(255)  not null,',
'   customer_name_upper     varchar2(255)  not null,',
'   --',
'   address                 varchar2(255),',
'   address_2               varchar2(255),',
'   city                    varchar2(255),',
'   state                   varchar2(255),',
'   postal_code             varchar2(255),',
'   country                 varchar2(255),',
'   --',
'   marquee_customer_yn     varchar2(1),',
'   --',
'   tags                    varchar2(4000),',
'   customer_profile        clob,',
'   web_site                varchar2(1000),',
'   stock_symbol            varchar2(30),',
'   sic                     varchar2(30),  -- standard industry code',
'   duns                    varchar2(30),  -- dun and bradstreet number',
'   --',
'   created               timestamp with time zone not null,',
'   created_by            varchar2(255) not null,',
'   updated               timestamp with time zone,',
'   updated_by            varchar2(255),',
'   --',
'   flex_n01                number,',
'   flex_n02                number,',
'   flex_n03                number,',
'   flex_n04                number,',
'   flex_d01                timestamp with time zone,',
'   flex_d02                timestamp with time zone,',
'   flex_d03                timestamp with time zone,',
'   flex_d04                timestamp with time zone,',
'   flex_01                 varchar2(4000),',
'   flex_02                 varchar2(4000),',
'   flex_03                 varchar2(4000),',
'   flex_04                 varchar2(4000),',
'   flex_05                 varchar2(4000),',
'   flex_06                 varchar2(4000),',
'   flex_07                 varchar2(4000),',
'   flex_08                 varchar2(4000),',
'   flex_clob               clob',
'   )',
'/',
'alter table eba_intrack_customers',
'   add constraint eba_intrack_customers_pk',
'       primary key (id)',
'/',
'create unique index eba_intrack_cust_uk on eba_intrack_customers(customer_name)',
'/',
'',
'',
'create or replace trigger biu_eba_intrack_customers',
'   before insert or update on eba_intrack_customers',
'   for each row',
'begin',
'      if :new.tags is not null then',
'            :new.tags := eba_intrack_fw.tags_cleaner(:new.tags);',
'      end if;',
'      if inserting then',
'         if :NEW.ID is null then',
'           select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'           into :new.id',
'           from dual;',
'         end if;',
'         :NEW.CREATED    := current_timestamp;',
'         :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'         :NEW.UPDATED    := current_timestamp;',
'         :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'         :new.row_version_number := 1;',
'         :new.customer_name_upper := trim(upper(:new.customer_name));',
'        eba_intrack_fw.tag_sync(',
'            p_new_tags      => :new.tags,',
'            p_old_tags      => null,',
'            p_content_type  => ''CUSTOMER'',',
'            p_content_id    => :new.id );',
'      end if;',
'',
'      if :new.row_key is null then',
'         select eba_intrack_fw.compress_int(eba_intrack_seq.nextval) into :new.row_key from dual;',
'      end if;',
'',
'      if updating then',
'         :NEW.UPDATED := current_timestamp;',
'         :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'         :new.row_version_number := nvl(:new.row_version_number,0) + 1;',
'         :new.customer_name_upper := trim(upper(:new.customer_name));',
'         eba_intrack_fw.tag_sync(',
'            p_new_tags      => :new.tags,',
'            p_old_tags      => :old.tags,',
'            p_content_type  => ''CUSTOMER'',',
'            p_content_id    => :new.id );',
'      end if;',
'end;',
'/',
'show errors',
'    ',
'insert into eba_intrack_customers (id,customer_name) values (1,''ACME'');',
'insert into eba_intrack_customers (id,customer_name) values (2,''Internal - IT'');',
'insert into eba_intrack_customers (id,customer_name) values (3,''Internal - Operations'');',
'insert into eba_intrack_customers (id,customer_name) values (4,''Internal - QA'');',
'insert into eba_intrack_customers (id,customer_name) values (5,''Internal - Development'');',
'commit;',
''))
);
wwv_flow_imp.component_end;
end;
/
