prompt --application/deployment/install/install_incidents_triggers
begin
--   Manifest
--     INSTALL: INSTALL-incidents triggers
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(2742716354452902733)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'incidents triggers'
,p_sequence=>300
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace trigger biu_eba_intrack_incidents',
'before insert or update on eba_intrack_incidents',
'for each row',
'begin',
'   if :new.tags is not null then',
'      :new.tags := eba_intrack_fw.tags_cleaner(:new.tags);',
'   end if;',
'   if inserting then',
'      if :NEW.ID is null then',
'         select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'           into :NEW.ID',
'           from dual;',
'      end if;',
'      if :new.CREATED is null then',
'           :NEW.CREATED := current_timestamp;',
'      end if;',
'      :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'      :new.row_version_number := 1;',
'   end if;',
'   --',
'   if inserting or updating then',
'      :NEW.UPDATED    := current_timestamp;',
'      :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'   end if;',
'   if updating then',
'      :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'   end if;',
'   if :new.incident_number is null then',
'       for c1 in (select eba_intrack_seq.nextval s from dual) loop',
'           :new.incident_number := eba_intrack_fw.compress_int(c1.s);',
'       end loop;',
'   end if;',
'',
'   if :new.severity_id is null then',
'      for c1 in (select id from eba_intrack_severity order by sequence_number desc) loop',
'          :new.severity_id := c1.id;',
'          exit;',
'      end loop;',
'   end if;',
'   if nvl(:new.status_id,0) != nvl(:old.status_id,0) then',
'       for c2 in (select status_code from eba_intrack_status where id = :new.status_id) loop',
'           :new.status_code := c2.status_code;',
'       end loop;',
'   end if;',
'   --',
'   if updating then',
'       --',
'       if :new.status_id is not null then',
'          for c3 in (select STATUS_TYPE from EBA_INTRACK_STATUS ',
'                     where id = :new.status_id ) loop',
'                  if c3.STATUS_TYPE = ''CLOSED'' then',
'                      :new.DATE_CLOSED := current_timestamp;',
'                  elsif c3.STATUS_TYPE = ''OPEN'' then',
'                      :new.DATE_CLOSED := null;',
'                  end if;',
'          end loop;',
'       end if;',
'       --',
'       if :new.DATE_CLOSED is not null and :old.date_closed is null then',
'          insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''CLOSE_DATE_CHANGE'', ''DATE_CLOSED'', null, ''Date closed automatically set'');',
'       end if;',
'       if :new.DATE_CLOSED is  null and :old.date_closed is not null then',
'          insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''CLOSE_DATE_CHANGE'', ''DATE_CLOSED'', ''Date closed automatically unset'', null);',
'       end if;',
'       --',
'       if nvl(:new.status_code,''x'') != nvl(:old.status_code,''x'') then',
'          insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''STATUS_CHANGE'', ''STATUS_CODE'', :old.status_id, :new.status_id);',
'       end if;',
'       if nvl(:new.ASSIGNED_TO_ID,0) != nvl(:old.ASSIGNED_TO_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''ASSIGNEE_CHANGE'', ''ASSIGNED_TO_ID'', :old.ASSIGNED_TO_ID, :new.ASSIGNED_TO_ID);',
'       end if;',
'       if nvl(:new.URGENCY_ID,0) != nvl(:old.URGENCY_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''URGENCY_CHANGE'', ''URGENCY_ID'', :old.URGENCY_ID, :new.URGENCY_ID);',
'       end if;',
'       if nvl(:new.SEVERITY_ID,0) != nvl(:old.SEVERITY_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''SEVERITY_CHANGE'', ''SEVERITY_ID'', :old.SEVERITY_ID, :new.SEVERITY_ID);',
'       end if;',
'       if nvl(:new.CATEGORY_ID,0) != nvl(:old.CATEGORY_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''CATEGORY_CHANGE'', ''CATEGORY_ID'', :old.CATEGORY_ID, :new.CATEGORY_ID);',
'       end if;',
'       if nvl(:new.TAGS,''0'') != nvl(:old.TAGS,''0'') then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''TAG_CHANGE'', ''TAGS'', :old.TAGS, :new.TAGS);',
'       end if;',
'       if nvl(:new.PRODUCT_ID,0) != nvl(:old.PRODUCT_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''PRODUCT_CHANGE'', ''PRODUCT_ID'', :old.PRODUCT_ID, :new.PRODUCT_ID);',
'       end if;',
'       if nvl(:new.CUSTOMER_ID,0) != nvl(:old.CUSTOMER_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''CUSTOMER_CHANGE'', ''CUSTOMER_ID'', :old.CUSTOMER_ID, :new.CUSTOMER_ID);',
'       end if;',
'       if nvl(:new.PRODUCT_VERSION_ID,0) != nvl(:old.PRODUCT_VERSION_ID,0) then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''PRODUCT_VERSION_CHANGE'', ''PRODUCT_VERSION_ID'', :old.PRODUCT_VERSION_ID, :new.PRODUCT_VERSION_ID);',
'       end if;',
'       if nvl(:new.SUBJECT,''0'') != nvl(:old.SUBJECT,''0'') then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''SUBJECT_CHANGE'', ''SUBJECT'', :old.SUBJECT, :new.SUBJECT);',
'       end if;',
'       if nvl(:new.BUG_NUMBER,''0'') != nvl(:old.BUG_NUMBER,''0'') then',
'            insert into eba_intrack_inc_followup ',
'            (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'            values ',
'            (:new.id, ''BUG_CHANGE'', ''BUG_NUMBER'', :old.BUG_NUMBER, :new.BUG_NUMBER);',
'       end if;',
'   end if;',
'   --',
'   eba_intrack_fw.tag_sync(',
'        p_new_tags      => :new.tags,',
'        p_old_tags      => :old.tags,',
'        p_content_type  => ''INCIDENT'',',
'        p_content_id    => :new.id );',
'end;',
'/',
'show errors',
'',
'create or replace trigger bd_eba_intrack_incidents',
'    before delete on eba_intrack_incidents',
'    for each row',
'begin',
'',
'    eba_intrack_fw.tag_sync(',
'        p_new_tags      => null,',
'        p_old_tags      => :old.tags,',
'        p_content_type  => ''INCIDENT'',',
'        p_content_id    => :old.id );',
'',
'end;',
'/',
'show errors',
'',
'',
''))
);
wwv_flow_imp.component_end;
end;
/
