prompt --application/deployment/install/upgrade_timestamp_fix_bugid_31352674
begin
--   Manifest
--     INSTALL: UPGRADE-TIMESTAMP Fix ( BUGID: 31352674)
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(428194653182670892)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'TIMESTAMP Fix ( BUGID: 31352674)'
,p_sequence=>140
,p_script_type=>'UPGRADE'
,p_condition_type=>'EXISTS'
,p_condition=>'select null from all_tab_cols where table_name like ''EBA_INTRACK_%'' and data_type = ''TIMESTAMP(6) WITH LOCAL TIME ZONE'''
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- This script fixes BUG 31352674, replacing all columns of type TIMESTAMP(6) WITH LOCAL TIME ZONE to TIMESTAMP WITH TIME ZONE',
'-- it also updates all application triggers where columns where updated with LOCALTIMESTAMP to CURRENT_TIMESTAMP',
'-- ',
'-- This upgrade script will only run if there are tables that start with ''EBA_INTRACK%'' with columns of data type',
'-- TIMESTAMP(6) WITH LOCAL TIME ZONE',
'',
'-- Start of Script',
'-- 1. Disable All Triggers',
'alter trigger "BI_EBA_INTRACK_ERRORS" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_ASSIGNEES" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_NOTE_BIU" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_USERS_BIU" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_USERS_BD" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_STATUS" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_PRODUCT" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_PREFERENCES_BIU" DISABLE;',
'/',
'alter trigger "BD_EBA_INTRACK_INCIDENTS" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_INCIDENTS" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_TZ_PREF" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_CATEGORY" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_GROUP" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_CUSTOMERS" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_SEVERITY" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_CLICKS_BIU" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_VERSION" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_URGENCY" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_USER_GROUP" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_NOTES" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_TAGS" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_INC_FOLLUP_BIU" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_FILES" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_FILES_BD" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_COUNTRIES" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_LINKS" DISABLE;',
'/',
'alter trigger "EBA_INTRACK_VERIFY_BIU_FER" DISABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_CUST_CON" DISABLE;',
'/',
'',
'-- 2. Add temporary timestamp columns',
'alter table EBA_INTRACK_ERRORS add (ERR_TIME1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_ASSIGNEES add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone,FLEX_D011 timestamp with time zone,FLEX_D021 timestamp with time zone,FLEX_D031 timestamp with time zone,FLEX_D041 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_NOTIFICATIONS add (DISPLAY_FROM1 timestamp with time zone,DISPLAY_UNTIL1 timestamp with time zone,CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_USERS add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_STATUS add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_PRODUCT add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_PREFERENCES add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_INCIDENTS add (SUBMITTED_ON1 timestamp with time zone,ASSIGNED_ON1 timestamp with time zone,DATE_CLOSED1 timestamp with time zone,FLEX_DATE_011 timestamp with time zone,FLEX_DATE_021 timestamp with time zone,FLEX_DATE_031 time'
||'stamp with time zone,FLEX_DATE_041 timestamp with time zone,CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_TZ_PREF add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_CATEGORY add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_GROUP add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_CUSTOMERS add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone,FLEX_D011 timestamp with time zone,FLEX_D021 timestamp with time zone,FLEX_D031 timestamp with time zone,FLEX_D041 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_SEVERITY add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_CLICKS add (VIEW_TIMESTAMP1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_VERSION add (RELEASE_DATE1 timestamp with time zone,CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_URGENCY add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_USER_GROUP add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_NOTES add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_TAGS add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_INC_FOLLOWUP add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_FILES add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_COUNTRIES add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_LINKS add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_VERIFICATIONS add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'alter table EBA_INTRACK_CUSTOMER_CONTACT add (CREATED1 timestamp with time zone,UPDATED1 timestamp with time zone)',
'/',
'',
'-- 3. Copy original column values into temporary column values',
'update EBA_INTRACK_ERRORS set ERR_TIME1 = ERR_TIME;',
'update EBA_INTRACK_ASSIGNEES set CREATED1 = CREATED,UPDATED1 = UPDATED,FLEX_D011 = FLEX_D01,FLEX_D021 = FLEX_D02,FLEX_D031 = FLEX_D03,FLEX_D041 = FLEX_D04;',
'update EBA_INTRACK_NOTIFICATIONS set DISPLAY_FROM1 = DISPLAY_FROM,DISPLAY_UNTIL1 = DISPLAY_UNTIL,CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_USERS set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_STATUS set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_PRODUCT set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_PREFERENCES set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_INCIDENTS set SUBMITTED_ON1 = SUBMITTED_ON,ASSIGNED_ON1 = ASSIGNED_ON,DATE_CLOSED1 = DATE_CLOSED,FLEX_DATE_011 = FLEX_DATE_01,FLEX_DATE_021 = FLEX_DATE_02,FLEX_DATE_031 = FLEX_DATE_03,FLEX_DATE_041 = FLEX_DATE_04,CREATED1 = CREATED'
||',UPDATED1 = UPDATED;',
'update EBA_INTRACK_TZ_PREF set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_CATEGORY set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_GROUP set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_CUSTOMERS set CREATED1 = CREATED,UPDATED1 = UPDATED,FLEX_D011 = FLEX_D01,FLEX_D021 = FLEX_D02,FLEX_D031 = FLEX_D03,FLEX_D041 = FLEX_D04;',
'update EBA_INTRACK_SEVERITY set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_CLICKS set VIEW_TIMESTAMP1 = VIEW_TIMESTAMP;',
'update EBA_INTRACK_VERSION set RELEASE_DATE1 = RELEASE_DATE,CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_URGENCY set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_USER_GROUP set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_NOTES set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_TAGS set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_INC_FOLLOWUP set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_FILES set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_COUNTRIES set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_LINKS set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_VERIFICATIONS set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'update EBA_INTRACK_CUSTOMER_CONTACT set CREATED1 = CREATED,UPDATED1 = UPDATED;',
'',
'-- 4. Drop original timestamp with local time zone columns',
'alter table EBA_INTRACK_ERRORS drop (ERR_TIME)',
'/',
'alter table EBA_INTRACK_ASSIGNEES drop (CREATED,UPDATED,FLEX_D01,FLEX_D02,FLEX_D03,FLEX_D04)',
'/',
'alter table EBA_INTRACK_NOTIFICATIONS drop (DISPLAY_FROM,DISPLAY_UNTIL,CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_USERS drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_STATUS drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_PRODUCT drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_PREFERENCES drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_INCIDENTS drop (SUBMITTED_ON,ASSIGNED_ON,DATE_CLOSED,FLEX_DATE_01,FLEX_DATE_02,FLEX_DATE_03,FLEX_DATE_04,CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_TZ_PREF drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_CATEGORY drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_GROUP drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_CUSTOMERS drop (CREATED,UPDATED,FLEX_D01,FLEX_D02,FLEX_D03,FLEX_D04)',
'/',
'alter table EBA_INTRACK_SEVERITY drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_CLICKS drop (VIEW_TIMESTAMP)',
'/',
'alter table EBA_INTRACK_VERSION drop (RELEASE_DATE,CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_URGENCY drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_USER_GROUP drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_NOTES drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_TAGS drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_INC_FOLLOWUP drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_FILES drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_COUNTRIES drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_LINKS drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_VERIFICATIONS drop (CREATED,UPDATED)',
'/',
'alter table EBA_INTRACK_CUSTOMER_CONTACT drop (CREATED,UPDATED)',
'/',
'',
'-- 5. Rename temporary columns back to original column names',
'alter table EBA_INTRACK_ERRORS rename column ERR_TIME1 to ERR_TIME',
'/',
'alter table EBA_INTRACK_ASSIGNEES rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_ASSIGNEES rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_ASSIGNEES rename column FLEX_D011 to FLEX_D01',
'/',
'alter table EBA_INTRACK_ASSIGNEES rename column FLEX_D021 to FLEX_D02',
'/',
'alter table EBA_INTRACK_ASSIGNEES rename column FLEX_D031 to FLEX_D03',
'/',
'alter table EBA_INTRACK_ASSIGNEES rename column FLEX_D041 to FLEX_D04',
'/',
'alter table EBA_INTRACK_NOTIFICATIONS rename column DISPLAY_FROM1 to DISPLAY_FROM',
'/',
'alter table EBA_INTRACK_NOTIFICATIONS rename column DISPLAY_UNTIL1 to DISPLAY_UNTIL',
'/',
'alter table EBA_INTRACK_NOTIFICATIONS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_NOTIFICATIONS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_USERS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_USERS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_STATUS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_STATUS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_PRODUCT rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_PRODUCT rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_PREFERENCES rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_PREFERENCES rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column SUBMITTED_ON1 to SUBMITTED_ON',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column ASSIGNED_ON1 to ASSIGNED_ON',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column DATE_CLOSED1 to DATE_CLOSED',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column FLEX_DATE_011 to FLEX_DATE_01',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column FLEX_DATE_021 to FLEX_DATE_02',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column FLEX_DATE_031 to FLEX_DATE_03',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column FLEX_DATE_041 to FLEX_DATE_04',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_INCIDENTS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_TZ_PREF rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_TZ_PREF rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_CATEGORY rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_CATEGORY rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_GROUP rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_GROUP rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_CUSTOMERS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_CUSTOMERS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_CUSTOMERS rename column FLEX_D011 to FLEX_D01',
'/',
'alter table EBA_INTRACK_CUSTOMERS rename column FLEX_D021 to FLEX_D02',
'/',
'alter table EBA_INTRACK_CUSTOMERS rename column FLEX_D031 to FLEX_D03',
'/',
'alter table EBA_INTRACK_CUSTOMERS rename column FLEX_D041 to FLEX_D04',
'/',
'alter table EBA_INTRACK_SEVERITY rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_SEVERITY rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_CLICKS rename column VIEW_TIMESTAMP1 to VIEW_TIMESTAMP',
'/',
'alter table EBA_INTRACK_VERSION rename column RELEASE_DATE1 to RELEASE_DATE',
'/',
'alter table EBA_INTRACK_VERSION rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_VERSION rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_URGENCY rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_URGENCY rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_USER_GROUP rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_USER_GROUP rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_NOTES rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_NOTES rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_TAGS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_TAGS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_INC_FOLLOWUP rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_INC_FOLLOWUP rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_FILES rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_FILES rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_COUNTRIES rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_COUNTRIES rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_LINKS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_LINKS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_VERIFICATIONS rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_VERIFICATIONS rename column UPDATED1 to UPDATED',
'/',
'alter table EBA_INTRACK_CUSTOMER_CONTACT rename column CREATED1 to CREATED',
'/',
'alter table EBA_INTRACK_CUSTOMER_CONTACT rename column UPDATED1 to UPDATED',
'/',
'',
'-- 6. Re-create all triggers and enable them.',
'create or replace TRIGGER BI_EBA_INTRACK_ERRORS',
'    before insert or update on EBA_INTRACK_ERRORS',
'    for each row',
'begin',
'    if :new.id is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'') into :new.id from dual;',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_ASSIGNEES',
'   before insert or update on EBA_INTRACK_ASSIGNEES',
'   for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'        into :new.id',
'        from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'        :new.assignee_name_upper := trim(upper(:new.assignee_name));',
'    end if;',
'    if :new.row_key is null then',
'        select eba_intrack_fw.compress_int(eba_intrack_seq.nextval) into :new.row_key from dual;',
'    end if;',
'    if updating then',
'        :NEW.UPDATED := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := nvl(:new.row_version_number,0) + 1;',
'        :new.assignee_name_upper := trim(upper(:new.assignee_name));',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_NOTE_BIU',
'    before insert or update on EBA_INTRACK_NOTIFICATIONS',
'    for each row',
'begin',
'    if inserting and :new.id is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'        into :new.id',
'        from dual;',
'    end if;',
'    if inserting then',
'        :new.created_by := nvl(v(''APP_USER''),USER);',
'        :new.created := current_timestamp;',
'        :new.updated_by := nvl(v(''APP_USER''),USER);',
'        :new.updated := current_timestamp;',
'        :new.row_version_number := 1;',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'        :new.updated_by := nvl(v(''APP_USER''),USER);',
'        :new.updated    := current_timestamp;',
'    end if;',
'    if :new.notification_type is null then',
'       :new.notification_type := ''MANUAL'';',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_USERS_BIU',
'    before insert or update on EBA_INTRACK_USERS',
'    for each row',
'begin',
'    if inserting then',
'        if :new.id is null then',
'            :new.id := eba_intrack.gen_id();',
'        end if;',
'        :new.created_by         := nvl(v(''APP_USER''), USER);',
'        :new.created            := current_timestamp;',
'        :new.row_version        := 1;',
'        if :new.account_locked is null then',
'            :new.account_locked := ''N'';    ',
'        end if;',
'    end if;',
'    if updating then',
'            :new.updated_by         := nvl(v(''APP_USER''), USER);',
'            :new.updated            := current_timestamp;',
'            :new.row_version        := nvl(:old.row_version,1) + 1;                                   ',
'    end if;',
'    -- Always store username as upper case',
'    :new.username := upper(:new.username);',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_USERS_BD',
'    before delete on EBA_INTRACK_USERS',
'    for each row',
'declare',
'    pragma autonomous_transaction;',
'begin',
'    -- Disallow deletes to a user''s own record unless last one.',
'    if v(''APP_USER'') = upper(:old.username) then',
'        for c1 in (',
'            select count(*) cnt',
'              from eba_intrack_users',
'             where id != :old.id )',
'        loop',
'            if c1.cnt > 0 then',
'                raise_application_error(-20002, ''Delete disallowed, you cannot delete your own access control details.'');',
'            end if;',
'        end loop;',
'    end if;    ',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_STATUS',
'    before insert or update on EBA_INTRACK_STATUS',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'            into :new.id',
'            from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.is_active is null then',
'        :new.is_active := ''Y'';',
'    end if;',
'    if :new.status_code is null then',
'        :new.status_code := upper(:new.status_name);',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_PRODUCT',
'    before insert or update on EBA_INTRACK_PRODUCT',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'            into :new.id',
'            from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.is_active is null then',
'        :new.is_active := ''Y'';',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_PREFERENCES_BIU',
'    before insert or update on EBA_INTRACK_PREFERENCES',
'    for each row',
'begin',
'    if inserting and :new.id is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'        into :new.id',
'        from dual;',
'    end if;',
'    if inserting then',
'        :new.created_by := nvl(v(''APP_USER''),USER);',
'        :new.created    := current_timestamp;',
'    end if;',
'    if updating then',
'        :new.updated_by := nvl(v(''APP_USER''),USER);',
'        :new.updated    := current_timestamp;',
'    end if;',
'    :new.preference_name := upper(:new.preference_name);',
'end;',
'/',
'',
'create or replace TRIGGER BD_EBA_INTRACK_INCIDENTS',
'    before delete on EBA_INTRACK_INCIDENTS',
'    for each row',
'begin',
'    eba_intrack_fw.tag_sync(',
'        p_new_tags      => null,',
'        p_old_tags      => :old.tags,',
'        p_content_type  => ''INCIDENT'',',
'        p_content_id    => :old.id );',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_INCIDENTS',
'    before insert or update on EBA_INTRACK_INCIDENTS',
'    for each row',
'begin',
'    if :new.tags is not null then',
'        :new.tags := eba_intrack_fw.tags_cleaner(:new.tags);',
'    end if;',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'            into :NEW.ID',
'            from dual;',
'        end if;',
'        if :new.CREATED is null then',
'            :NEW.CREATED := current_timestamp;',
'        end if;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    --',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.incident_number is null then',
'        for c1 in (select eba_intrack_seq.nextval s from dual) loop',
'            :new.incident_number := eba_intrack_fw.compress_int(c1.s);',
'        end loop;',
'    end if;',
'    if :new.severity_id is null then',
'        for c1 in (select id from eba_intrack_severity order by sequence_number desc) loop',
'            :new.severity_id := c1.id;',
'            exit;',
'        end loop;',
'    end if;',
'    if nvl(:new.status_id,0) != nvl(:old.status_id,0) then',
'        for c2 in (select status_code from eba_intrack_status where id = :new.status_id) loop',
'            :new.status_code := c2.status_code;',
'        end loop;',
'    end if;',
'    --',
'    if updating then',
'        --',
'        if :new.status_id is not null then',
'            for c3 in (select STATUS_TYPE from EBA_INTRACK_STATUS ',
'                        where id = :new.status_id ) loop',
'                    if c3.STATUS_TYPE = ''CLOSED'' then',
'                        :new.DATE_CLOSED := current_timestamp;',
'                    elsif c3.STATUS_TYPE = ''OPEN'' then',
'                        :new.DATE_CLOSED := null;',
'                    end if;',
'            end loop;',
'        end if;',
'        --',
'        if :new.DATE_CLOSED is not null and :old.date_closed is null then',
'            insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''CLOSE_DATE_CHANGE'', ''DATE_CLOSED'', null, ''Date closed automatically set'');',
'        end if;',
'        if :new.DATE_CLOSED is  null and :old.date_closed is not null then',
'            insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''CLOSE_DATE_CHANGE'', ''DATE_CLOSED'', ''Date closed automatically unset'', null);',
'        end if;',
'        --',
'        if nvl(:new.status_code,''x'') != nvl(:old.status_code,''x'') then',
'            insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''STATUS_CHANGE'', ''STATUS_CODE'', :old.status_id, :new.status_id);',
'        end if;',
'        if nvl(:new.ASSIGNED_TO_ID,0) != nvl(:old.ASSIGNED_TO_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''ASSIGNEE_CHANGE'', ''ASSIGNED_TO_ID'', :old.ASSIGNED_TO_ID, :new.ASSIGNED_TO_ID);',
'        end if;',
'        if nvl(:new.URGENCY_ID,0) != nvl(:old.URGENCY_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''URGENCY_CHANGE'', ''URGENCY_ID'', :old.URGENCY_ID, :new.URGENCY_ID);',
'        end if;',
'        if nvl(:new.SEVERITY_ID,0) != nvl(:old.SEVERITY_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''SEVERITY_CHANGE'', ''SEVERITY_ID'', :old.SEVERITY_ID, :new.SEVERITY_ID);',
'        end if;',
'        if nvl(:new.CATEGORY_ID,0) != nvl(:old.CATEGORY_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''CATEGORY_CHANGE'', ''CATEGORY_ID'', :old.CATEGORY_ID, :new.CATEGORY_ID);',
'        end if;',
'        if nvl(:new.TAGS,''0'') != nvl(:old.TAGS,''0'') then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''TAG_CHANGE'', ''TAGS'', :old.TAGS, :new.TAGS);',
'        end if;',
'        if nvl(:new.PRODUCT_ID,0) != nvl(:old.PRODUCT_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''PRODUCT_CHANGE'', ''PRODUCT_ID'', :old.PRODUCT_ID, :new.PRODUCT_ID);',
'        end if;',
'        if nvl(:new.CUSTOMER_ID,0) != nvl(:old.CUSTOMER_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''CUSTOMER_CHANGE'', ''CUSTOMER_ID'', :old.CUSTOMER_ID, :new.CUSTOMER_ID);',
'        end if;',
'        if nvl(:new.PRODUCT_VERSION_ID,0) != nvl(:old.PRODUCT_VERSION_ID,0) then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''PRODUCT_VERSION_CHANGE'', ''PRODUCT_VERSION_ID'', :old.PRODUCT_VERSION_ID, :new.PRODUCT_VERSION_ID);',
'        end if;',
'        if nvl(:new.SUBJECT,''0'') != nvl(:old.SUBJECT,''0'') then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''SUBJECT_CHANGE'', ''SUBJECT'', :old.SUBJECT, :new.SUBJECT);',
'        end if;',
'        if nvl(:new.BUG_NUMBER,''0'') != nvl(:old.BUG_NUMBER,''0'') then',
'                insert into eba_intrack_inc_followup ',
'                (incident_id,follow_up_type,status_column,status_old_val,status_new_val ) ',
'                values ',
'                (:new.id, ''BUG_CHANGE'', ''BUG_NUMBER'', :old.BUG_NUMBER, :new.BUG_NUMBER);',
'        end if;',
'    end if;',
'    --',
'    eba_intrack_fw.tag_sync(',
'            p_new_tags      => :new.tags,',
'            p_old_tags      => :old.tags,',
'            p_content_type  => ''INCIDENT'',',
'            p_content_id    => :new.id );',
'    end;',
'    /',
'',
'    create or replace TRIGGER BIU_EBA_INTRACK_TZ_PREF',
'        before insert or update on EBA_INTRACK_TZ_PREF',
'        for each row',
'    begin',
'    if :new."ID" is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'') into :new.id from dual;',
'    end if;',
'    if inserting then',
'        :new.created := current_timestamp;',
'        :new.created_by := nvl(wwv_flow.g_user,user);',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'        :new.row_version_number := 1;',
'    elsif updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if inserting or updating then',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'    end if;',
'    if :new.TIMEZONE_PREFERENCE is null then',
'        :new.timezone_preference := ''UTC'';',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_CATEGORY',
'    before insert or update on EBA_INTRACK_CATEGORY',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.is_active is null then',
'        :new.is_active := ''Y'';',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_GROUP',
'    before insert or update on EBA_INTRACK_GROUP',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_CUSTOMERS',
'    before insert or update on EBA_INTRACK_CUSTOMERS',
'    for each row',
'begin',
'    if :new.tags is not null then',
'        :new.tags := eba_intrack_fw.tags_cleaner(:new.tags);',
'    end if;',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'     '))
);
wwv_flow_imp_shared.append_to_install_script(
 p_id=>wwv_flow_imp.id(428194653182670892)
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'   :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'        :new.customer_name_upper := trim(upper(:new.customer_name));',
'    eba_intrack_fw.tag_sync(',
'        p_new_tags      => :new.tags,',
'        p_old_tags      => null,',
'        p_content_type  => ''CUSTOMER'',',
'        p_content_id    => :new.id );',
'    end if;',
'    if :new.row_key is null then',
'        select eba_intrack_fw.compress_int(eba_intrack_seq.nextval) into :new.row_key from dual;',
'    end if;',
'    if updating then',
'        :NEW.UPDATED := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := nvl(:new.row_version_number,0) + 1;',
'        :new.customer_name_upper := trim(upper(:new.customer_name));',
'        eba_intrack_fw.tag_sync(',
'        p_new_tags      => :new.tags,',
'        p_old_tags      => :old.tags,',
'        p_content_type  => ''CUSTOMER'',',
'        p_content_id    => :new.id );',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_SEVERITY',
'    before insert or update on EBA_INTRACK_SEVERITY',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.is_active is null then',
'        :new.is_active := ''Y'';',
'    end if;',
'    if :new.sequence_number is null then',
'        select nvl(max(sequence_number),0) + 1 into :new.sequence_number from eba_intrack_severity;',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_CLICKS_BIU',
'    before insert on EBA_INTRACK_CLICKS',
'    for each row',
'begin',
'    if :new.id is null then',
'        :new.id := eba_intrack_seq.nextval;',
'    end if;',
'    :new.view_timestamp := current_timestamp;',
'    :new.app_username := nvl(v(''APP_USER''),user);',
'    :new.app_session := v(''APP_SESSION'');',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_VERSION',
'    before insert or update on EBA_INTRACK_VERSION',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number :=  1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.is_active is null then',
'        :new.is_active := ''Y'';',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_URGENCY',
'    before insert or update on EBA_INTRACK_URGENCY',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.is_active is null then',
'        :new.is_active := ''Y'';',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_USER_GROUP',
'    before insert or update on EBA_INTRACK_USER_GROUP',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_NOTES ',
'    before insert or update on EBA_INTRACK_NOTES',
'    for each row',
'begin',
'    if :new."ID" is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'') into :new.id from dual;',
'    end if;',
'    if inserting then',
'        :new.created := current_timestamp;',
'        :new.created_by := nvl(wwv_flow.g_user,user);',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'        :new.row_version_number := 1;',
'    elsif updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if inserting or updating then',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_TAGS',
'   before insert or update on EBA_INTRACK_TAGS',
'   for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :NEW.UPDATED := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_INC_FOLLUP_BIU',
'    before insert or update on EBA_INTRACK_INC_FOLLOWUP',
'    for each row',
'begin',
'    if inserting and :new.id is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'          into :new.id',
'          from dual;',
'    end if;',
'    if inserting then',
'        :new.created_by := nvl(v(''APP_USER''),USER);',
'        :new.created := current_timestamp;',
'        :new.row_version_number := 1;',
'    end if;',
'    if updating then',
'        :new.updated_by := nvl(v(''APP_USER''),USER);',
'        :new.updated := current_timestamp;',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if :new.follow_up_type is null then',
'        :new.follow_up_type := ''TEXT'';',
'    end if;',
'    if :new.row_key is null then',
'       for c1 in (select eba_intrack_seq.nextval s from dual) loop',
'           :new.row_key := eba_intrack_fw.compress_int(c1.s);',
'       end loop;',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_FILES',
'    before insert or update on EBA_INTRACK_FILES',
'    for each row',
'begin',
'    if (inserting or updating) and nvl(dbms_lob.getlength(:new.file_blob),0) > 15728640 then',
'        raise_application_error(-20000, ''The size of the uploaded file was over 15MB. Please upload a smaller file.'');',
'    end if;',
'    if :new.tags is not null then',
'        :new.tags := eba_intrack_fw.tags_cleaner(:new.tags);',
'    end if;',
'    if :new.id is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'') into :new.id from dual;',
'    end if;',
'    if inserting then',
'        :new.created := current_timestamp;',
'        :new.created_by := nvl(wwv_flow.g_user,user);',
'        :new.row_version_number := 1;',
'    elsif updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if inserting or updating then',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'    end if;',
'    eba_intrack_fw.tag_sync(',
'        p_new_tags      => :new.tags,',
'        p_old_tags      => :old.tags,',
'        p_content_type  => ''FILE'',',
'        p_content_id    => :new.id);',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_FILES_BD',
'    before delete on EBA_INTRACK_FILES',
'    for each row',
'begin',
'    eba_intrack_fw.tag_sync(',
'        p_new_tags      => null,',
'        p_old_tags      => :old.tags,',
'        p_content_type  => ''FILE'',',
'        p_content_id    => :old.id );',
'end eba_intrack_files_bd;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_COUNTRIES',
'    before insert or update on EBA_INTRACK_COUNTRIES',
'    for each row',
'begin',
'    if inserting and :new.id is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'') into :new.id from dual;',
'    end if;',
'    if inserting then',
'        :new.row_version_number := 1;',
'        :NEW.CREATED := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'        :NEW.UPDATED := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_LINKS',
'    before insert or update on EBA_INTRACK_LINKS',
'    for each row',
'begin',
'    if :new."ID" is null then',
'        select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'') into :new.id from dual;',
'    end if;',
'    if inserting then',
'        :new.created := current_timestamp;',
'        :new.created_by := nvl(wwv_flow.g_user,user);',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'        :new.row_version_number := 1;',
'    elsif updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    if inserting or updating then',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(wwv_flow.g_user,user);',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER EBA_INTRACK_VERIFY_BIU_FER',
'    before insert or update on EBA_INTRACK_VERIFICATIONS',
'    for each row',
'begin',
'    if :new.id is null then',
'        :new.id := eba_intrack_seq.nextval;',
'    end if;',
'    if inserting then',
'        :new.created := current_timestamp;',
'        :new.created_by := nvl(apex_application.g_user,user);',
'    end if;',
'    if inserting or updating then',
'        :new.updated := current_timestamp;',
'        :new.updated_by := nvl(apex_application.g_user,user);',
'    end if;',
'end;',
'/',
'',
'create or replace TRIGGER BIU_EBA_INTRACK_CUST_CON',
'    before insert or update on EBA_INTRACK_CUSTOMER_CONTACT',
'    for each row',
'begin',
'    if inserting then',
'        if :NEW.ID is null then',
'            select to_number(sys_guid(),''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')',
'              into :new.id',
'              from dual;',
'        end if;',
'        :NEW.CREATED    := current_timestamp;',
'        :NEW.CREATED_BY := nvl(v(''APP_USER''),USER);',
'        :new.row_version_number := 1;',
'    end if;',
'    if inserting or updating then',
'        :NEW.UPDATED    := current_timestamp;',
'        :NEW.UPDATED_BY := nvl(v(''APP_USER''),USER);',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    :new.email := lower(:new.email);',
'end;',
'/',
'',
'alter trigger "BI_EBA_INTRACK_ERRORS" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_ASSIGNEES" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_NOTE_BIU" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_USERS_BIU" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_USERS_BD" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_STATUS" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_PRODUCT" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_PREFERENCES_BIU" ENABLE;',
'/',
'alter trigger "BD_EBA_INTRACK_INCIDENTS" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_INCIDENTS" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_TZ_PREF" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_CATEGORY" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_GROUP" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_CUSTOMERS" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_SEVERITY" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_CLICKS_BIU" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_VERSION" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_URGENCY" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_USER_GROUP" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_NOTES" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_TAGS" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_INC_FOLLUP_BIU" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_FILES" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_FILES_BD" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_COUNTRIES" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_LINKS" ENABLE;',
'/',
'alter trigger "EBA_INTRACK_VERIFY_BIU_FER" ENABLE;',
'/',
'alter trigger "BIU_EBA_INTRACK_CUST_CON" ENABLE;',
'/',
''))
);
wwv_flow_imp.component_end;
end;
/
