prompt --application/deployment/install/upgrade_new_sample_data_procedure
begin
--   Manifest
--     INSTALL: UPGRADE-New sample data procedure
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>14430312641517637
,p_default_application_id=>101
,p_default_id_offset=>26419087940450297
,p_default_owner=>'WKSP_XTD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(1514282748493115527)
,p_install_id=>wwv_flow_imp.id(2719947952873449465)
,p_name=>'New sample data procedure'
,p_sequence=>90
,p_script_type=>'UPGRADE'
,p_condition_type=>'ALWAYS'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace procedure eba_intrack_load_sample',
'as',
'    x varchar2(255) := null;',
'begin',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 3,',
'        p_severity_id             => 3,',
'        p_category_id             => 3,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Logout button did not log out in firefox or IE, or Safari'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, FIREFOX, IE, Safari'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 8)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 3,',
'        p_severity_id             => 3,',
'        p_category_id             => 3,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''user interface looked odd when viewing with Firefox'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, FIREFOX'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 8)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 3,',
'        p_severity_id             => 3,',
'        p_category_id             => 3,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''user interface looked odd when viewing with IE'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, IE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 8)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 3,',
'        p_severity_id             => 3,',
'        p_category_id             => 3,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Administration application unable to purge sample data'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, DATA'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 8)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 3,',
'        p_severity_id             => 3,',
'        p_category_id             => 3,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Administration application not viewable in FF or IE'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, UI, Firefox, IE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 7)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 2,',
'        p_severity_id             => 2,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Unable to find incident using search functionality'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 7)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 2,',
'        p_severity_id             => 2,',
'        p_category_id             => 2,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''unable to determine status'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 1)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 2,',
'        p_severity_id             => 3,',
'        p_category_id             => 2,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''trying to attach a file and getting an error'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 2)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Cameron'',',
'        p_contact_last_name       => ''Case'',',
'        p_contact_email           => ''cameron.case@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 2,',
'        p_severity_id             => 1,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''unable to view tag cloud'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 3)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 3,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Collin'',',
'        p_contact_last_name       => ''Corbin'',',
'        p_contact_email           => ''collin.corbin@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 1,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''unable to attach file'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 1)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 3,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Allison'',',
'        p_contact_last_name       => ''Adams'',',
'        p_contact_email           => ''allison.adams@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 2,',
'        p_product_version_id      => 21,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 1,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''creating new record returned error'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, UI'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 1)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 3,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Adam'',',
'        p_contact_last_name       => ''Atkinson'',',
'        p_contact_email           => ''adam.atkinson@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 2,',
'        p_product_version_id      => 21,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 1,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''creating new record returned an error'',',
'        p_incident_description    => ''unable to proceed'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, UI'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 1)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 1,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Bill'',',
'        p_contact_last_name       => ''Benson'',',
'        p_contact_email           => ''bill.benson@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 2,',
'        p_product_version_id      => 21,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 1,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Unable to install'',',
'        p_incident_description    => ''have no idea how to install'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, INSTALL'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 6)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Bob'',',
'        p_contact_last_name       => ''Benson'',',
'        p_contact_email           => ''bob.benson@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 3,',
'        p_product_version_id      => 31,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 2,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Unable to logout'',',
'        p_incident_description    => ''do not see any logout page'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE, UI, FIREFOX, IE, SAFARI, LOGOUT, ERROR'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 5)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 2,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Bob'',',
'        p_contact_last_name       => ''Barber'',',
'        p_contact_email           => ''bob.barber@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 3,',
'        p_product_version_id      => 31,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 2,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Unable to login'',',
'        p_incident_description    => ''do not see any login page'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 4)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 3,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Brenda'',',
'        p_contact_last_name       => ''Bert'',',
'        p_contact_email           => ''brenda.bert@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 3,',
'        p_product_version_id      => 31,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 2,',
'        p_category_id             => 1,',
'        p_status_id               => 1,',
'        --',
'        p_subject                 => ''Widget appears to display using an odd character set'',',
'        p_incident_description    => ''do not see any login page'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 3)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 3,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Bonnie'',',
'        p_contact_last_name       => ''Brown'',',
'        p_contact_email           => ''bonnie.brown@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 2,',
'        p_category_id             => 1,',
'        p_status_id               => 2,',
'        --',
'        p_subject                 => ''Widget appears to display using an unexpected character set'',',
'        p_incident_description    => ''do not see any login page'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 2)',
'        ;',
'    commit;',
'',
'    x := eba_intrack_incident.create_ticket (',
'        p_customer_id             => 4,',
'        p_customer_name           => null,',
'        p_customer_web_site       => null,',
'        p_customer_address        => null,',
'        p_customer_city           => null,',
'        p_customer_state          => null,',
'        p_customer_postal_code    => null,',
'        --                      ',
'        p_contact_id              => null,',
'        p_contact_first_name      => ''Buster'',',
'        p_contact_last_name       => ''Boswell'',',
'        p_contact_email           => ''buster.boswell@maildomain.com'',',
'        p_contact_department      => null,',
'        p_contact_phone           => null,',
'        p_contact_phone_type      => null,',
'        --                      ',
'        p_product_id              => 1,',
'        p_product_version_id      => 1,',
'        p_product_additional_info => null,',
'        --',
'        p_urgency_id              => 1,',
'        p_severity_id             => 2,',
'        p_category_id             => 1,',
'        p_status_id               => 2,',
'        --',
'        p_subject                 => ''Applying changes gives error'',',
'        p_incident_description    => ''I click and it doesnt work'',',
'        p_bug_number              => null,',
'        p_additional_info         => null,',
'        --',
'        p_tags                    => ''SAMPLE'',',
'        p_create_date_override    => to_date(to_char(current_timestamp,''DD-MON-YYYY''),''DD-MON-YYYY'') - 1)',
'        ;',
'',
'',
'    begin',
'        for c1 in (',
'            select id',
'              from eba_intrack_incidents',
'             where status_id < 5',
'             order by created desc )',
'        loop',
'            update eba_intrack_incidents set status_id = 5 where id = c1.id;',
'            exit;',
'        end loop;',
'        commit;',
'    end;',
'',
'',
'    begin',
'        for c1 in (',
'            select id',
'              from eba_intrack_incidents',
'             where status_id < 5',
'             order by created desc )',
'        loop',
'            update eba_intrack_incidents set status_id = 6 where id = c1.id;',
'            exit;',
'        end loop;',
'        commit;',
'    end;',
'',
'',
'    begin',
'        for c1 in (',
'            select id',
'              from eba_intrack_incidents',
'             where status_id < 5',
'             order by created desc )',
'        loop',
'            update eba_intrack_incidents set status_id = 7 where id = c1.id;',
'            exit;',
'        end loop;',
'        commit;',
'    end;',
'',
'    ',
'end;',
'/',
'show errors',
''))
);
wwv_flow_imp.component_end;
end;
/
