prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/incident_actions.sql
@@application/shared_components/navigation/lists/preferences.sql
@@application/shared_components/navigation/lists/look_up_values.sql
@@application/shared_components/navigation/lists/wiz_progress.sql
@@application/shared_components/navigation/lists/incidents_reports.sql
@@application/shared_components/navigation/lists/administration.sql
@@application/shared_components/navigation/lists/additional_reports.sql
@@application/shared_components/navigation/lists/access_control_2.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/mobile_menu.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/listentry.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/application_sentry.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/set_time_zone.sql
@@application/shared_components/logic/application_processes/trim_all_page_items.sql
@@application/shared_components/logic/application_items/a01.sql
@@application/shared_components/logic/application_items/a02.sql
@@application/shared_components/logic/application_items/a03.sql
@@application/shared_components/logic/application_items/application_title.sql
@@application/shared_components/logic/application_items/cnt_01.sql
@@application/shared_components/logic/application_items/cnt_02.sql
@@application/shared_components/logic/application_items/cnt_03.sql
@@application/shared_components/logic/application_items/cnt_04.sql
@@application/shared_components/logic/application_items/cnt_05.sql
@@application/shared_components/logic/application_items/cnt_06.sql
@@application/shared_components/logic/application_items/cnt_07.sql
@@application/shared_components/logic/application_items/last_view.sql
@@application/shared_components/logic/application_items/tz.sql
@@application/shared_components/logic/application_computations/a01.sql
@@application/shared_components/logic/application_computations/a02.sql
@@application/shared_components/logic/application_computations/a03.sql
@@application/shared_components/logic/application_computations/application_title.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_control_scope.sql
@@application/shared_components/user_interface/lovs/access_control_scope1.sql
@@application/shared_components/user_interface/lovs/access_levels.sql
@@application/shared_components/user_interface/lovs/assignees.sql
@@application/shared_components/user_interface/lovs/category.sql
@@application/shared_components/user_interface/lovs/customer.sql
@@application/shared_components/user_interface/lovs/notification_type.sql
@@application/shared_components/user_interface/lovs/product_version.sql
@@application/shared_components/user_interface/lovs/products.sql
@@application/shared_components/user_interface/lovs/rows.sql
@@application/shared_components/user_interface/lovs/severity.sql
@@application/shared_components/user_interface/lovs/severity_without_code.sql
@@application/shared_components/user_interface/lovs/status.sql
@@application/shared_components/user_interface/lovs/tickets.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/urgency.sql
@@application/shared_components/user_interface/lovs/username_format.sql
@@application/shared_components/user_interface/lovs/users.sql
@@application/shared_components/user_interface/lovs/yes_no.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_translated_message.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_minicalendar.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_validator.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_completeness.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_status.sql
@@application/shared_components/plugins/region_type/com_oracle_auth_administration.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_html5_bar_chart.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_warning.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_timelinestatuslist.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_tag_cloud.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00092.sql
@@application/pages/page_00101.sql
@@application/pages/page_00175.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_set_plscope_settings.sql
@@application/deployment/install/install_eba_intrack_spec.sql
@@application/deployment/install/install_error_log.sql
@@application/deployment/install/upgrade_framework_package_spec.sql
@@application/deployment/install/install_framework_spec.sql
@@application/deployment/install/upgrade_framework_body.sql
@@application/deployment/install/install_seqence.sql
@@application/deployment/install/upgrade_eba_intrack_package.sql
@@application/deployment/install/install_time_zone.sql
@@application/deployment/install/install_access_control_tables.sql
@@application/deployment/install/upgrade_fix_acl_user_levels.sql
@@application/deployment/install/install_countries.sql
@@application/deployment/install/install_notifications.sql
@@application/deployment/install/install_preferences_tables.sql
@@application/deployment/install/upgrade_username_format.sql
@@application/deployment/install/upgrade_remove_help_table.sql
@@application/deployment/install/install_tags_table.sql
@@application/deployment/install/upgrade_remove_old_unique_subject_constraint.sql
@@application/deployment/install/upgrade_unique_ticket_names_subjects.sql
@@application/deployment/install/install_group_tables.sql
@@application/deployment/install/upgrade_unique_attachment_filenames.sql
@@application/deployment/install/install_urgency_table.sql
@@application/deployment/install/upgrade_remove_unique_link_names_constraint.sql
@@application/deployment/install/install_severity_table.sql
@@application/deployment/install/upgrade_new_sample_data_procedure.sql
@@application/deployment/install/install_status_table.sql
@@application/deployment/install/upgrade_click_counting_table.sql
@@application/deployment/install/install_category_table.sql
@@application/deployment/install/upgrade_content_validation_table.sql
@@application/deployment/install/install_product_table.sql
@@application/deployment/install/upgrade_set_first_run_preference.sql
@@application/deployment/install/install_product_version_table.sql
@@application/deployment/install/upgrade_make_customer_mandatory_on_incidents.sql
@@application/deployment/install/upgrade_timestamp_fix_bugid_31352674.sql
@@application/deployment/install/install_framework_body.sql
@@application/deployment/install/install_customers_table.sql
@@application/deployment/install/install_customer_contacts_table.sql
@@application/deployment/install/install_incidents_table.sql
@@application/deployment/install/install_product_version_function.sql
@@application/deployment/install/install_incident_package_spec.sql
@@application/deployment/install/install_incident_package_body.sql
@@application/deployment/install/install_incident_follow_up.sql
@@application/deployment/install/install_incidents_triggers.sql
@@application/deployment/install/install_val_email_fmt.sql
@@application/deployment/install/install_assignees.sql
@@application/deployment/install/install_incidents_view.sql
@@application/deployment/install/install_files_table.sql
@@application/deployment/install/install_links.sql
@@application/deployment/install/install_notes.sql
@@application/deployment/install/install_sample_data.sql
@@application/deployment/install/install_eba_intrack_body.sql
@@application/deployment/install/install_click_counting_table.sql
@@application/deployment/install/install_content_validation_table.sql
@@application/deployment/install/install_set_first_run_preference.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
