/*
================================================================================
  02_setup_monitoring_otomatis.sql

  TUJUAN
  ------
  Setup SEKALI JALAN untuk monitoring kapasitas Oracle Database 23ai Free
  secara otomatis, supaya tidak keburu melewati batas 12 GB storage saat
  masih pakai edisi Free.

  Referensi konsep & threshold:
  https://github.com/iwanhe/pandawa/blob/main/oracle-licensing/20260225_Komparasi_6_Platform_Database.md

  OBJEK YANG DIBUAT (di schema tempat script ini dijalankan, mis. ADMIN)
  ------------------------------------------------------------------------
    1. Tabel     STORAGE_ALERT_LOG    -> histori hasil cek (untuk tren)
    2. View      V_STORAGE_MONITOR    -> snapshot kapasitas saat ini + status
    3. Package   PKG_STORAGE_MONITOR  -> logic cek + catat + tampilkan
    4. Scheduler job JOB_STORAGE_CAPACITY_CHECK -> jalan otomatis tiap hari

  Script ini AMAN dijalankan berulang kali (idempotent): tabel histori
  yang sudah ada tidak akan dihapus/ditimpa, view/package akan di-replace,
  dan job scheduler akan dibuat ulang dengan definisi terbaru.

  CARA PAKAI
  ----------
      sql ADMIN/password@localhost:1521/FREEPDB1 @02_setup_monitoring_otomatis.sql

  Butuh privilege: CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE JOB.
  User ADMIN bawaan Oracle 23ai Free biasanya sudah punya semua ini.

  CATATAN JAM JOB
  ----------------
  Job dijadwalkan jam 07:00 menurut timezone SERVER database (bukan
  timezone client Anda). Kalau server sudah di-set ke WIB (Asia/Jakarta),
  berarti jam 07:00 WIB. Ubah BYHOUR di STEP 4 kalau perlu jam lain.
================================================================================
*/

SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON

PROMPT
PROMPT ================================================================
PROMPT  STEP 1/4 - Tabel histori STORAGE_ALERT_LOG
PROMPT ================================================================

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE storage_alert_log (
            log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            check_date  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            used_gb     NUMBER(10,3),
            free_gb     NUMBER(10,3),
            pct_used    NUMBER(5,1),
            status      VARCHAR2(20),
            message     VARCHAR2(4000)
        )';
    DBMS_OUTPUT.PUT_LINE('OK  - Tabel STORAGE_ALERT_LOG dibuat.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('SKIP - Tabel STORAGE_ALERT_LOG sudah ada, histori lama tetap dipertahankan.');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT
PROMPT ================================================================
PROMPT  STEP 2/4 - View V_STORAGE_MONITOR (snapshot kapasitas saat ini)
PROMPT ================================================================

-- Schema bawaan Oracle (SYS, SYSTEM, APEX_xxxxxx, MDSYS, XDB, WMSYS, dst)
-- dikecualikan otomatis lewat DBA_USERS.ORACLE_MAINTAINED, jadi view ini
-- tidak perlu diupdate manual kalau versi APEX / skema internal berubah.
CREATE OR REPLACE VIEW v_storage_monitor AS
SELECT
    ROUND(SUM(s.bytes) / 1024 / 1024 / 1024, 3)            AS used_gb,
    ROUND(12 - SUM(s.bytes) / 1024 / 1024 / 1024, 3)        AS free_gb,
    ROUND(SUM(s.bytes) / 1024 / 1024 / 1024 / 12 * 100, 1)  AS pct_used,
    CASE
        WHEN SUM(s.bytes) / 1024 / 1024 / 1024 >= 11   THEN 'CRITICAL'
        WHEN SUM(s.bytes) / 1024 / 1024 / 1024 >= 9.6  THEN 'WARNING'
        WHEN SUM(s.bytes) / 1024 / 1024 / 1024 >= 8    THEN 'CAUTION'
        ELSE 'NORMAL'
    END                                                       AS status
FROM dba_segments s
JOIN dba_users u ON u.username = s.owner
WHERE u.oracle_maintained = 'N';
/

PROMPT OK  - View V_STORAGE_MONITOR siap. Contoh pakai: SELECT * FROM v_storage_monitor;

PROMPT
PROMPT ================================================================
PROMPT  STEP 3/4 - Package PKG_STORAGE_MONITOR
PROMPT ================================================================

CREATE OR REPLACE PACKAGE pkg_storage_monitor AS

    c_limit_gb    CONSTANT NUMBER := 12;   -- batas hard Oracle 23ai Free
    c_caution_gb  CONSTANT NUMBER := 8;    -- mulai pantau aktif
    c_warning_gb  CONSTANT NUMBER := 9.6;  -- perlu cleanup
    c_critical_gb CONSTANT NUMBER := 11;   -- tindakan segera

    -- Cek kapasitas terkini, catat ke STORAGE_ALERT_LOG, dan (opsional)
    -- tampilkan hasilnya via DBMS_OUTPUT. Ini prosedur yang dipanggil
    -- oleh scheduler job harian.
    PROCEDURE check_capacity(p_verbose IN BOOLEAN DEFAULT TRUE);

    -- Ambil status kapasitas terakhir sebagai VARCHAR2, untuk dipakai
    -- oleh proses lain (mis. kondisi di APEX, atau script eksternal
    -- yang query tabel/fungsi ini).
    FUNCTION get_latest_status RETURN VARCHAR2;

    -- Tampilkan N histori cek terakhir ke layar.
    PROCEDURE show_history(p_rows IN PLS_INTEGER DEFAULT 10);

END pkg_storage_monitor;
/

CREATE OR REPLACE PACKAGE BODY pkg_storage_monitor AS

    PROCEDURE check_capacity(p_verbose IN BOOLEAN DEFAULT TRUE) IS
        l_used_gb  NUMBER;
        l_free_gb  NUMBER;
        l_pct_used NUMBER;
        l_status   VARCHAR2(20);
        l_message  VARCHAR2(4000);
    BEGIN
        SELECT used_gb, free_gb, pct_used, status
          INTO l_used_gb, l_free_gb, l_pct_used, l_status
          FROM v_storage_monitor;

        l_message := 'Pemakaian storage: ' || TO_CHAR(l_used_gb) || ' GB dari '
                     || TO_CHAR(c_limit_gb) || ' GB (' || TO_CHAR(l_pct_used)
                     || '%). Sisa: ' || TO_CHAR(l_free_gb) || ' GB.';

        INSERT INTO storage_alert_log (used_gb, free_gb, pct_used, status, message)
        VALUES (l_used_gb, l_free_gb, l_pct_used, l_status, l_message);

        COMMIT;

        IF p_verbose THEN
            DBMS_OUTPUT.PUT_LINE('[' || l_status || '] ' || l_message);
            IF l_status IN ('WARNING', 'CRITICAL') THEN
                DBMS_OUTPUT.PUT_LINE('  -> Segera cek breakdown per schema/tablespace '
                                      || '(lihat 01_cek_kapasitas_manual.sql) dan '
                                      || 'pertimbangkan archive/purge data lama.');
            END IF;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            IF p_verbose THEN
                DBMS_OUTPUT.PUT_LINE('Tidak ada data dari V_STORAGE_MONITOR (cek hak akses DBA_SEGMENTS/DBA_USERS).');
            END IF;
    END check_capacity;

    FUNCTION get_latest_status RETURN VARCHAR2 IS
        l_status VARCHAR2(20);
    BEGIN
        SELECT status
          INTO l_status
          FROM (
              SELECT status
                FROM storage_alert_log
               ORDER BY check_date DESC
          )
         WHERE ROWNUM = 1;

        RETURN l_status;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'UNKNOWN';
    END get_latest_status;

    PROCEDURE show_history(p_rows IN PLS_INTEGER DEFAULT 10) IS
    BEGIN
        FOR r IN (
            SELECT *
              FROM (
                  SELECT TO_CHAR(check_date, 'YYYY-MM-DD HH24:MI') AS check_date,
                         used_gb, pct_used, status
                    FROM storage_alert_log
                   ORDER BY check_date DESC
              )
             WHERE ROWNUM <= p_rows
        ) LOOP
            DBMS_OUTPUT.PUT_LINE(r.check_date || '  |  ' || r.used_gb || ' GB  |  '
                                  || r.pct_used || '%  |  ' || r.status);
        END LOOP;
    END show_history;

END pkg_storage_monitor;
/

PROMPT OK  - Package PKG_STORAGE_MONITOR siap.

PROMPT
PROMPT ================================================================
PROMPT  STEP 4/4 - Scheduler job harian (jam 07:00, timezone server DB)
PROMPT ================================================================

BEGIN
    DBMS_SCHEDULER.DROP_JOB(job_name => 'JOB_STORAGE_CAPACITY_CHECK', force => TRUE);
    DBMS_OUTPUT.PUT_LINE('INFO - Job lama ditemukan dan dihapus, akan dibuat ulang.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -27475 THEN
            DBMS_OUTPUT.PUT_LINE('INFO - Belum ada job sebelumnya, lanjut membuat baru.');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'JOB_STORAGE_CAPACITY_CHECK',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'PKG_STORAGE_MONITOR.CHECK_CAPACITY',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; BYHOUR=7; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        comments        => 'Cek harian kapasitas storage Oracle 23ai Free (limit 12GB), catat ke STORAGE_ALERT_LOG.'
    );
    DBMS_OUTPUT.PUT_LINE('OK  - Job JOB_STORAGE_CAPACITY_CHECK dibuat & aktif (jalan tiap hari jam 07:00 waktu server DB).');
END;
/

PROMPT
PROMPT ================================================================
PROMPT  VERIFIKASI SETUP
PROMPT ================================================================

PROMPT -- Jalankan satu kali sekarang untuk memastikan semua berfungsi:
SET SERVEROUTPUT ON
EXEC pkg_storage_monitor.check_capacity;

PROMPT
PROMPT -- Status job scheduler:
COLUMN job_name FORMAT A30
COLUMN next_run_date FORMAT A30
SELECT job_name, enabled, state, next_run_date
FROM   user_scheduler_jobs
WHERE  job_name = 'JOB_STORAGE_CAPACITY_CHECK';

PROMPT
PROMPT -- Histori cek terakhir:
COLUMN check_date FORMAT A18
COLUMN status FORMAT A10
SELECT TO_CHAR(check_date, 'YYYY-MM-DD HH24:MI') AS check_date,
       used_gb, pct_used, status
FROM   storage_alert_log
ORDER  BY check_date DESC
FETCH FIRST 10 ROWS ONLY;

PROMPT
PROMPT Setup selesai. Mulai sekarang PKG_STORAGE_MONITOR.CHECK_CAPACITY akan
PROMPT jalan otomatis tiap hari dan tercatat di STORAGE_ALERT_LOG.
PROMPT
PROMPT Cek manual kapan saja dengan salah satu perintah ini:
PROMPT   EXEC pkg_storage_monitor.check_capacity;
PROMPT   EXEC pkg_storage_monitor.show_history(10);
PROMPT   SELECT * FROM v_storage_monitor;
PROMPT   SELECT pkg_storage_monitor.get_latest_status FROM dual;
PROMPT
