select 
 tb.* ,
inv_convert.inv_um_convert (tb.ITEM_ID, 'BAL', NVL(:P_UOM,'BAL'))  *  tb.QTY_PO AS PO_QTY,
inv_convert.inv_um_convert (tb.ITEM_ID, 'BAL', NVL(:P_UOM,'BAL'))  *  tb.QTY_GRV AS GRV_QTY                                                                                 
 from (
SELECT po.po_header_id, pol.po_line_id, pol.item_id, PV.VENDOR_NAME_ALT AS PRINSIPAL, PO.SEGMENT1 AS PO_NUMBER, 
             RH.RECEIPT_NUM, RH.COMMENTS,
             RH.SHIPMENT_NUM, -- MISWAN ADD 9 JAN 25
             RH.ATTRIBUTE1 PLAT_NOMOR,  -- MISWAN ADD 9 JAN 25
             RH.ATTRIBUTE2 NAMA_DRIVER,  -- MISWAN ADD 9 JAN 25
             RH.ATTRIBUTE3 EKSPEDISI,   -- MISWAN ADD 9 JAN 25          
    TRUNC(PO.CREATION_DATE) AS PO_DATE,
    TO_CHAR(RH.SHIPPED_DATE,'DD-MM-RRRR') || ' - ' || TO_CHAR(TO_DATE(PO.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS'),'DD-MM-RRRR') AS PERIODE_KIRIM,
   --TO_CHAR(TO_DATE(RH.SHIPPED_DATE,'RRRR/MM/DD HH24:MI:SS'),'DD-MM-RRRR') || ' - ' || TO_CHAR(TO_DATE(PO.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS'),'DD-MM-RRRR') AS PERIODE_KIRIM,    
    POL.ITEM_DESCRIPTION AS BRAND,
    --RT.QUANTITY AS GRV_QTY, 
    RT.UNIT_OF_MEASURE AS DUOM, 
    NVL(:P_UOM,'BAL') AS UOM,
    RT.LOCATION_ID, 
    HL1.DESCRIPTION LOC_FROM, 
    RT.ORGANIZATION_ID, RH.SHIP_TO_ORG_ID, HOU.NAME SHIP_TO,
    RT.DELIVER_TO_LOCATION_ID,
    HL2.DESCRIPTION LOC_TO,
    RL.TO_SUBINVENTORY AS LOKASI, 
    RH.PACKING_SLIP AS NO_FAKTUR, RH.SHIPPED_DATE AS TGL_KIRIM, TRUNC(RT.TRANSACTION_DATE) AS TGL_TERIMA, 
        (select minggu from  xtd_period_week_v where (trunc(RT.TRANSACTION_DATE) between tanggal_awal_minggu_real and tanggal_akhir_minggu_real) 
        and rownum = 1) WEEK,
    PO.ORG_ID, RT.TRANSACTION_ID,
    RT.TRANSACTION_TYPE,
    POL.QUANTITY AS PO_QTY_LINES,      
     (select sum(quantity)  from PO_LINES_ALL pla where pla.po_header_id = po.po_header_id and pla.item_id=pol.item_id and cancel_flag ='N') QTY_PO,
    SUM(CASE WHEN RT.TRANSACTION_TYPE ='RETURN TO VENDOR' THEN RT.QUANTITY * (-1) ELSE RT.QUANTITY END ) AS QTY_GRV,         
    papf.full_name received_by
FROM 
    PO_HEADERS_ALL PO, 
    PO_LINES_ALL POL,
    RCV_SHIPMENT_HEADERS RH, 
    RCV_SHIPMENT_LINES RL,
    RCV_TRANSACTIONS RT, 
    per_all_people_f  papf,
    AP_SUPPLIERS PV,
    MTL_SYSTEM_ITEMS_B MSI, 
    HR_LOCATIONS HL1, 
    HR_LOCATIONS HL2, HR_ORGANIZATION_UNITS HOU
WHERE 1= 1
    AND RL.ITEM_ID=MSI.INVENTORY_ITEM_ID
    AND MSI.SEGMENT1 LIKE'RK'
    AND RH.SHIP_TO_ORG_ID = HOU.ORGANIZATION_ID 
    AND RT.LOCATION_ID = HL1.LOCATION_ID 
    AND RT.DELIVER_TO_LOCATION_ID = HL2.LOCATION_ID
    AND MSI.ORGANIZATION_ID = RT.ORGANIZATION_ID 
    AND PO.PO_HEADER_ID = POL.PO_HEADER_ID
    AND PO.VENDOR_ID = PV.VENDOR_ID
    AND RH.SHIPMENT_HEADER_ID = RL.SHIPMENT_HEADER_ID
    AND RT.SHIPMENT_HEADER_ID = RL.SHIPMENT_HEADER_ID
    AND RT.SHIPMENT_LINE_ID = RL.SHIPMENT_LINE_ID
    AND RT.PO_LINE_ID=POL.PO_LINE_ID
    AND RT.TRANSACTION_TYPE IN('DELIVER','RETURN TO VENDOR')
    AND rt.employee_id             = papf.person_id
    AND PO.ORG_ID= NVL(:P_ORG_ID, PO.ORG_ID)
    AND TRUNC(RT.TRANSACTION_DATE) >= :TGL1
    AND TRUNC(RT.TRANSACTION_DATE) <= :TGL2
--    AND PO.SEGMENT1 LIKE DECODE (:P_PO_NO,NULL,'%',:P_PO_NO)
--    and  RL.ITEM_ID = nvl(:ITEM_ID, RL.ITEM_ID)
GROUP BY  po.po_header_id, pol.po_line_id, pol.item_id, 
    HL1.DESCRIPTION , papf.full_name , 
    RT.ORGANIZATION_ID, RH.SHIP_TO_ORG_ID, HOU.NAME ,
    HL2.DESCRIPTION ,
    RT.LOCATION_ID, RH.COMMENTS,
     RT.TRANSACTION_TYPE,
    RT.DELIVER_TO_LOCATION_ID,
    PV.VENDOR_NAME_ALT , PO.SEGMENT1 , 
    TRUNC(PO.CREATION_DATE),
    TO_CHAR(RH.SHIPPED_DATE,'DD-MM-RRRR') || ' - ' || TO_CHAR(TO_DATE(PO.ATTRIBUTE4,'RRRR/MM/DD HH24:MI:SS'),'DD-MM-RRRR')  ,
    POL.QUANTITY, POL.ITEM_DESCRIPTION,
    RT.UNIT_OF_MEASURE,
    RL.TO_SUBINVENTORY ,
    RH.PACKING_SLIP , RH.SHIPPED_DATE, TRUNC(RT.TRANSACTION_DATE),
    PO.ORG_ID, RH.RECEIPT_NUM, RT.TRANSACTION_ID,
    RH.SHIPMENT_NUM, -- MISWAN ADD 9 JAN 25
             RH.ATTRIBUTE1,  -- MISWAN ADD 9 JAN 25
             RH.ATTRIBUTE2,  -- MISWAN ADD 9 JAN 25
             RH.ATTRIBUTE3   -- MISWAN ADD 9 JAN 25        
--ORDER BY 1, RH.RECEIPT_NUM 
) tb  order by PRINSIPAL, RECEIPT_NUM; 